language: php

php:
    - '7.2'
    - '7.4'

before_script:
    - composer self-update
    - composer install --prefer-dist --no-interaction

script:
    - vendor/bin/phpstan analyse --no-progress -c phpstan.neon
    - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no
